	
	
	<script type="text/javascript">
		$(document).ready(function (){
			$("#fab_f").hide();

			$("#idFabricante").change( function (){
				value = $("#idFabricante").val();
				//window.alert(value);
				if($("#idFabricante").val() == "outro"){
					$("#fab_f").show();
				}else{
					$("#fab_f").hide();
				}
			});
		});
	</script>
	
	<script type="text/javascript">
		$(document).ready(function (){
			$("#mod_m").hide();

			$("#idModelo").change( function (){
				value = $("#idModelo").val();
				//window.alert(value);
				if($("#idModelo").val() == "outro"){
					$("#mod_m").show();
				}else{
					$("#mod_m").hide();
				}
			});
		});
	</script>
	
	<script type="text/javascript">

		$(document).ready(function (){

			$("#tipo").change( function(){
				var id = $("#tipo").val();

				$.ajax({
					url: '<?= $this->baseUrl ?>/produtos/carregarmodelos',
					data: 'idTipo='+id,
					type:  'GET',
					dataType: 'html',
			        cache: false,
			        async: false,
			        success: function( data ) {
				        $("#idModelo").html(data);
			        }
				});
			} );
		});
	</script>
	
<div id="form" style="padding-left: 25%; width:700px;">
	<form method="POST" action="<?=$this->baseUrl() ?>/produtos/inserir" class="form-horizontal">
		<fieldset>
		<h3 class="bs-callout bs-callout-info">Adicionar Produto</h3>
		<br />
		<div class="control-group">
							
			<div class="form-group">	
				<label for="tipo" class="col-sm-4 control-label">Tipo:</label>							
				<select id="tipo" class="form-control col-sm-8" name="tipo" style="width: 200px;">
				<?php foreach($this->tipos as $t):?>
					<option value="<?php echo $t["id"];?>"><?php echo $t["tipo"];?></option>
				<?php endforeach;?>	
				</select>	
																		
			</div>
								
			<div class="form-group">	
				<label for="idFabricante" class="col-sm-4 control-label">Fabricante:</label>
				<select id="idFabricante" class="form-control col-sm-8" name="idFabricante" style="width: 200px;">
					<?php foreach($this->fabricantes as $f):?>
						<option value="<?php echo $f["id"];?>"><?php echo $f["fabricante"];?></option>
					<?php endforeach;?>	
						<option value="outro">Outro</option>
				</select>
				<input type="text" class="form-control col-sm-8"  name="fab_f" id="fab_f" 
						style="width: 200px; margin-top:5px; margin-left: 145px;" />
			</div>
								
			<div class="form-group">	
				<label for="idModelo" class="col-sm-4 control-label">Modelo:</label>
					<select id="idModelo" class="form-control col-sm-8" name="idModelo" style="width: 200px;">
						<option value="outro">Outro</option>
					</select>
					<input type="text" class="form-control col-sm-8"  name="mod_m" id="mod_m" 
							style="width: 200px; margin-top:5px; margin-left: 145px;" />
			</div>
								
			<div class="form-group">		
				<label for="quantidade" class="col-sm-4 control-label" >Quantidade:</label>
				<input type="text" class="form-control col-sm-8"  name="quantidade" id="quantidade" style="width: 60px;" required/>
			</div>		
			
			<div class="form-group">
				<label for="custoTotal" class="col-sm-4 control-label" >Custo Total:</label>
				<input type="text" class="form-control col-sm-8"  name="custoTotal"  id="custoTotal" style="width: 100px;"/>
			</div>
			
			<div class="form-group">		
				<label for="custoProjetado" class="col-sm-4 control-label" >Custo Projetado:</label>
				<input type="text" class="form-control col-sm-8"  name="custoProjetado"  id="custoProjetado" style="width: 100px;"/>
			</div>
			
			<div class="form-group">		
				<label for="observacao" class="col-sm-4 control-label">Observações:</label>
				<textarea class="form-control col-sm-8"  name="observacao"  id="observacao" style="width: 250px;" rows='5'></textarea>
			</div>
								
			<div class="form-group pull-right">
				<div class="col-sm-offset-2 col-sm-10">	
					<input type="submit" class="btn btn-danger" value="Adicionar" style="width: 100px;"/>
				</div>					
			</div>
								
		</div><!-- .control-group -->
						
		</fieldset>
	</form>
</div><!-- #form -->
				