<form action="<?=$this->baseUrl ?>/login/login" class="form-signin" role="form" method="post">
	
	<h2 class="form-signin-heading">Login:</h2>
	
	<input type="text" class="form-control" placeholder="login" required autofocus name="login">
	<input type="password" class="form-control" placeholder="senha" required name="senha">
	
	<button class="btn btn-lg btn-primary btn-block" type="submit" name="logar">Logar</button>
		
</form>